### ISSUE TITLE
Multiple lick values in coins list being used for each coin

### ISSUE THREAD

**Issue by ninjaWhippet** [daisy613/LHPControl#1]
When a liquidation event comes through and is displayed in the websocket log window (and websocket log file) it compares every lick value set acrtoss the coins in the c oins list for that liquidation even.

Tested with 9 paiurs and across these 9 there are 4 different lick values across these coins (100, 250, 500 and 750). Refer attached log where it displays that for a coin liquidation it is checking the lick value for each of these and not what is set for that coin (in 
this case CRV has a Lick of 250).

It doesn't look to be consistent and happen all the time for all pairs, so far its only the once for CRV attached (others are ok so far and successful trades have also been made).

[binance-ninjaWhippet LH Pro 1.77 GUI Test-W_out.log](https://github.com/daisy613/LHPControl/files/5721686/binance-ninjaWhippet.LH.Pro.1.77.GUI.Test-W_out.log)

**Comment by daisy613** [comment]
Hmm, this is definitely not an issue with LHPC. Remember, all that LHPC does is update the coins.json file. The file looks correct (doesn't have multiple values for each coin). The way to test it is to run plain bot (1.77) on the same coins.json and see if you get the same issue.

**Comment by ninjaWhippet** [comment]
Thanks, I'll package up the log files and raise as a bug on Gnomes github for LH. Unfortunately its intermittent, but I'll point out/provide screenshots of the relevant dates/time where it happens for Gnome to look in to. This bug existed in a previous version (1.74 or 1.75 I think) so hopefully its only a matter of reinstating that fix.
