### ISSUE TITLE
"Update All" button dosen't work

### ISSUE THREAD

**Issue by G2000E** [daisy613/LHPControl#10]
So, fresh install of lickhunter 1.76, toying around with LHPC...
I tried to input different values into the boxes nothing works, i get a message saying "you need to input all the values"
I didn't even turn it on yet just clicked save changes a few times.

[debugData.txt](https://github.com/daisy613/LHPControl/files/5731911/debugData.txt)

![bug_lhpc](https://user-images.githubusercontent.com/65676778/102930936-b1e41080-449d-11eb-9aa7-0dd388d30b58.png)

**Comment by daisy613** [comment]
The new version has fixed this issue. :)
