### ISSUE TITLE
to ad

### ISSUE THREAD

**Issue by imqct** [daisy613/LHPControl#14]

**Comment by daisy613** [comment]
A little more info? :)

**Comment by imqct** [comment]
Open orders are not added when changing modes.

Eg. If I have a current open order, changing of coin list or trading modes (from 3 to 1) does not add the open order coin into coin list.

It prevents DCA from continuing.

**Comment by daisy613** [comment]
Latest release fixes that issue. It was not affecting DCA, it was only a display issue. The coins.json was updated appropriately
