### ISSUE TITLE
Binance Get issue

### ISSUE THREAD

**Issue by Xeckin** [daisy613/LHPControl#16]
Looking at error log: 
ERROR - 2020-12-29 23:03:05,046 - binance GET https://fapi.binance.com/fapi/v1/positionRisk?timestamp=1609300972839&recvWindow=5000&signature=e7a5069351e43660d7f0fac275a2b6078403795be8b60335952203a6fa4479f0 503 Service Unavailable {"timestamp":1609300986882,"path":"/fapi/v1/positionRisk","msg":"Unknown error, please check your request or try again later."}

**Comment by daisy613** [comment]
This is an LH issue. Please submit on Gnome's github.
