### ISSUE TITLE
OpenOrderIsolation or MaxOpen not update coin.js

### ISSUE THREAD

**Issue by whitedevil0303** [daisy613/LHPControl#17]
Thanks for your effort to make the bot more awesome,

I notice, in 1.77.3 when OpenOrderIsolation or MaxOpen turn to True, LHPC will, update coin.js to same with Open Order list, to prevent Open Order another coins, but in 1.77.4, LHPC not update coin.js.

it is bug or i miss understanding LHPC works?

**Comment by daisy613** [comment]
Latest release fixes that issue.
