### ISSUE TITLE
v1.77.5 still not showing Coins

### ISSUE THREAD

**Issue by Xeckin** [daisy613/LHPControl#19]
V1.77.5 still not showing the coins being traded in the GUI.  I can restart the bot a few times and it will show until the refresh happens every 5 mins.  Screenshot below
![image](https://user-images.githubusercontent.com/73088071/103427277-e76bb680-4b8d-11eb-9285-8e44f9521301.png)

**Comment by daisy613** [comment]
Latest release fixes that issue.
