### ISSUE TITLE
Enhancement - User settable "refresh" time for position checking?

### ISSUE THREAD

**Issue by ninjaWhippet** [daisy613/LHPControl#2]
Enchancement:

How often does the script "refresh" and check for number open positions, account balance used by open positions, etc?

Early days of Doosj this was set quite low (2-5 second refresh from memory), then a later version this increased to 15 seconds (I found this far too long and dropped it back to 2-3). If it is in the order of 15 seconds (if it still works like this) is it possible to make this a user definable setting?

If the PC is powerful enough you should be able to lower this and it will prevent open positions exceeding maxopenpositions and kick in isolation mode quicker. During big market moves position size can grow fast and so can open positions.

**Comment by daisy613** [comment]
Added custom refreshTime field to user editable values in v1.77.0a
