### ISSUE TITLE
v1.77.5 does not show correct balance

### ISSUE THREAD

**Issue by Xeckin** [daisy613/LHPControl#20]
Ive restarted the bot a few times to see if it would pull the correct balance but it did not.  Looks to be a few USD off.  See screenshot below:
![image](https://user-images.githubusercontent.com/73088071/103444456-5dc3f380-4c36-11eb-911f-426a4b2f6fa0.png)

**Comment by daisy613** [comment]
Can you see if the latest release makes it more accurate? Please keep in mind that the API results are always a few minutes off.
