### ISSUE TITLE
coins.json not updated after switching maxorders/isolation from active to inactive

### ISSUE THREAD

**Issue by imqct** [daisy613/LHPControl#22]
Hi,

I'm running 1.77.5. Been noticing that the coins.json are not updating after switching from active to inactive.

Restarting LHPControl does not help.

The following process will rebuild the coins.json.
1) Stop Bot
2) Edit Coins
3) Save Changes
4) Start Bot

**Comment by imqct** [comment]
Just an update running new version 1.77.7.

Same behaviour observed after maxtradepairs or isolation reached. Does not update coins.json after becoming inactive.

Coins.json in GUI is also not accurate as it appears to be showing all the coins in varPairs.json. The list in GUI does not disappear now.

**Comment by daisy613** [comment]
Fixed in the latest release

**Comment by imqct** [comment]
Hi, it is still displaying the same issue.

I have attached my debug data.

MaxOrders 3 - Current coin list is 3 although no open positions.
[debugData.txt](https://github.com/daisy613/LHPControl/files/5847639/debugData.txt)

**Comment by imqct** [comment]
Just tried running as Administrator to test.

Will update if that's the issue.

Update. Still the same. Not updating with tradingmode 3.
