### ISSUE TITLE
Bug configuration coin.json

### ISSUE THREAD

**Issue by Simpleclic** [daisy613/LHPControl#24]
Hello everyone, I'm currently encountering a bug on Lickhunter, I'm configuring my Coin by LHPControle and when I launch it, each coin appears in triple with different settings. Has anyone ever had a problem? Do you know how to resolve it?

![image](https://user-images.githubusercontent.com/72610548/104235102-c55b1980-5454-11eb-8b31-ad01b7a0f78f.png)

so the bot is using wrong parameters

![image](https://user-images.githubusercontent.com/72610548/104235145-d441cc00-5454-11eb-9305-a3b4c3c59fe3.png)

![image](https://user-images.githubusercontent.com/72610548/104235165-dad04380-5454-11eb-9615-a29da1655c44.png)

**Comment by daisy613** [comment]
This is solved in the new release.

**Comment by Simpleclic** [comment]
Yeah it's okey, Thanks for you help !
