### ISSUE TITLE
[Errno 22] Invalid argument

### ISSUE THREAD

**Issue by Overider2021** [daisy613/LHPControl#27]
Found out that latest version of LH wwith latest version of LHPC crashed on my VPS, when I was checking the logs I had 249MB of a log mostly with this message:

ERROR - 2021-01-19 19:06:12,384 - [Errno 22] Invalid argument

I will attach all my logs and the debug.
In case its nothing related feel free to close.

Thanks for your efforts and keep the good work.
[debugData.txt](https://github.com/daisy613/LHPControl/files/5839257/debugData.txt)
[other logs.zip](https://github.com/daisy613/LHPControl/files/5839275/other.logs.zip)

**Comment by daisy613** [comment]
I cannot open the Zip file. Please reupload.

**Comment by Overider2021** [comment]
Try use 7z pls I just downloaded and it worked fine.

**Comment by daisy613** [comment]
Please redownload Gnome's LH 1.80 and LHPC 1.80.0 and try again.
