### ISSUE TITLE
LHPC.exe creates a new invisible process every time it is launched and exited

### ISSUE THREAD

**Issue by xuvvy** [daisy613/LHPControl#28]
Every time LHPC.exe is launched it creates a new process and then another one when it is exited, these processes are invisible in regular Task Manger but are actually running and using up resources.

As seen in Process Lasso:
![image](https://user-images.githubusercontent.com/21984783/105215565-b4e02880-5b51-11eb-9df2-ed22f5647133.png)

This issue was present in previous versions and still is in the latest.

**Comment by daisy613** [comment]
Please submit your DebugData.txt file.

**Comment by xuvvy** [comment]
Attached the debugData.txt file.

[debugData.txt](https://github.com/daisy613/LHPControl/files/5844497/debugData.txt)

**Comment by xuvvy** [comment]
I ran the `get-process | ? {$_.name -like "*LHPC*"} | select name,id,path` command in PowerShell several times - while having LHPC running, after closing it and after closing and opening it several times.

This is the command while LHPC.exe is running:
![image](https://user-images.githubusercontent.com/21984783/105219237-86188100-5b56-11eb-9546-5d06e0d941f2.png)

This is the same command after closing it:
![image](https://user-images.githubusercontent.com/21984783/105219604-f0312600-5b56-11eb-98c3-5b3486526e8a.png)

After opening it and closing several times:
![image](https://user-images.githubusercontent.com/21984783/105219788-266ea580-5b57-11eb-8d38-78faa1ccd69e.png)

**Comment by daisy613** [comment]
The process eventually gets closed.
