### ISSUE TITLE
Settings getting deleted

### ISSUE THREAD

**Issue by shadowerwtas** [daisy613/LHPControl#8]
Problem: Settings are missing as seen on screenshot when I run LHPC.
![image](https://user-images.githubusercontent.com/16911104/102917896-a6d5b400-448e-11eb-8ac0-7682fb60417b.png)

When it occurs: Usually when I download new version of the program. Once just closed the bot and reopened it.
Procedure: I stop the bot, wait few seconds and then close the program. Wait few more seconds and from latest release I download and replace the LHPC.exe file. I run the file and settings aren't there.

Last time happened was when I downloaded v1.77.0d. I run the exe and the settings were there, then I started the bot and everything seemed to work. After an hour I noticed that not a single trade happened while there were licks and on profit log I saw the "ERROR - 2020-12-22 18:29:51,277 - Expecting value: line 1 column 1 (char 0)". I stopped the bot, waited few seconds, closed the program and started it again, the settings gone missing! This last time it erased the coins list too!

[debugData.txt](https://github.com/daisy613/LHPControl/files/5731326/debugData.txt)

**Comment by daisy613** [comment]
1.77.0e fixes it.
